//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace twd_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEntity
    {
        public CourseEntity()
        {
            this.CourseEntityGrades = new HashSet<CourseEntityGrade>();
            this.EntityParameters = new HashSet<EntityParameter>();
        }
    
        public short courseEntityID { get; set; }
        public string courseEntity1 { get; set; }
        public Nullable<short> courseEntityWeight { get; set; }
        public short courseId { get; set; }
        public Nullable<bool> showGrades { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseEntityGrade> CourseEntityGrades { get; set; }
        public virtual ICollection<EntityParameter> EntityParameters { get; set; }
    }
}
