//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace twd_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseEntities = new HashSet<CourseEntity>();
            this.TWD_User = new HashSet<TWD_User>();
        }
    
        public short courseId { get; set; }
        public string course1 { get; set; }
        public Nullable<short> courseWeight { get; set; }
        public short moduleId { get; set; }
        public Nullable<int> courseHours { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<CourseEntity> CourseEntities { get; set; }
        public virtual ICollection<TWD_User> TWD_User { get; set; }
    }
}
