//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace twd_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intake
    {
        public Intake()
        {
            this.Modules = new HashSet<Module>();
            this.TWD_User = new HashSet<TWD_User>();
        }
    
        public short intakeId { get; set; }
        public string intake1 { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<TWD_User> TWD_User { get; set; }
    }
}
