//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace twd_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public short moduleId { get; set; }
        public string module1 { get; set; }
        public Nullable<short> moduleWeight { get; set; }
        public short intakeId { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Intake Intake { get; set; }
    }
}
